//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestiunea_stocurilor
{
    using System;
    using System.Collections.Generic;
    
    public partial class BonConsum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BonConsum()
        {
            this.ProdusConsum = new HashSet<ProdusConsum>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdDepozit { get; set; }
        public Nullable<int> IdProdus { get; set; }
        public string Numar { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
    
        public virtual Depozit Depozit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdusConsum> ProdusConsum { get; set; }
    }
}
