//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestiunea_stocurilor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factura()
        {
            this.AvizExpeditie = new HashSet<AvizExpeditie>();
            this.ContinutFactura = new HashSet<ContinutFactura>();
            this.NIR = new HashSet<NIR>();
        }
    
        public int Id { get; set; }
        public string Numar { get; set; }
        public string Serie { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Explicatii { get; set; }
        public Nullable<int> IdPartenerClient { get; set; }
        public Nullable<int> IdPartenerFurnizor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvizExpeditie> AvizExpeditie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContinutFactura> ContinutFactura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NIR> NIR { get; set; }
        public virtual Partener Partener { get; set; }
        public virtual Partener Partener1 { get; set; }
    }
}
