//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestiunea_stocurilor
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfFirma
    {
        public int Id { get; set; }
        public string Denumire { get; set; }
        public string CUI { get; set; }
        public string Adresa { get; set; }
        public string ContBancar { get; set; }
        public Nullable<System.DateTime> DataStocInitial { get; set; }
    }
}
