//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestiunea_stocurilor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marfa
    {
        public int IdProdus { get; set; }
        public Nullable<decimal> PretStandardMf { get; set; }
    
        public virtual Produs Produs { get; set; }
    }
}
