//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestiunea_stocurilor
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BD1Entities1 : DbContext
    {
        public BD1Entities1()
            : base("name=BD1Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BonConsum> BonConsum { get; set; }
        public virtual DbSet<BonTransfer> BonTransfer { get; set; }
        public virtual DbSet<ContinutFactura> ContinutFactura { get; set; }
        public virtual DbSet<ContinutNIR> ContinutNIR { get; set; }
        public virtual DbSet<Depozit> Depozit { get; set; }
        public virtual DbSet<Gestionar> Gestionar { get; set; }
        public virtual DbSet<Marfa> Marfa { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<MateriePrima> MateriePrima { get; set; }
        public virtual DbSet<Partener> Partener { get; set; }
        public virtual DbSet<Produs> Produs { get; set; }
        public virtual DbSet<ProdusConsum> ProdusConsum { get; set; }
        public virtual DbSet<ProdusExpeditie> ProdusExpeditie { get; set; }
        public virtual DbSet<ProdusFinit> ProdusFinit { get; set; }
        public virtual DbSet<ProdusGestionat> ProdusGestionat { get; set; }
        public virtual DbSet<ProdusTransfer> ProdusTransfer { get; set; }
        public virtual DbSet<NIR> NIR { get; set; }
        public virtual DbSet<AvizExpeditie> AvizExpeditie { get; set; }
        public virtual DbSet<Factura> Factura { get; set; }
        public virtual DbSet<InfFirma> InfFirma { get; set; }
    
        [DbFunction("BD1Entities1", "FStatusDepozit")]
        public virtual IQueryable<FStatusDepozit_Result> FStatusDepozit()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FStatusDepozit_Result>("[BD1Entities1].[FStatusDepozit]()");
        }
    
        [DbFunction("BD1Entities1", "FGestionarDepozit")]
        public virtual IQueryable<FGestionarDepozit_Result> FGestionarDepozit()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FGestionarDepozit_Result>("[BD1Entities1].[FGestionarDepozit]()");
        }
    
        [DbFunction("BD1Entities1", "StocCurentT")]
        public virtual IQueryable<Nullable<int>> StocCurentT(Nullable<int> idProdus, Nullable<int> idDepozit, Nullable<System.DateTime> data)
        {
            var idProdusParameter = idProdus.HasValue ?
                new ObjectParameter("IdProdus", idProdus) :
                new ObjectParameter("IdProdus", typeof(int));
    
            var idDepozitParameter = idDepozit.HasValue ?
                new ObjectParameter("IdDepozit", idDepozit) :
                new ObjectParameter("IdDepozit", typeof(int));
    
            var dataParameter = data.HasValue ?
                new ObjectParameter("Data", data) :
                new ObjectParameter("Data", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Nullable<int>>("[BD1Entities1].[StocCurentT](@IdProdus, @IdDepozit, @Data)", idProdusParameter, idDepozitParameter, dataParameter);
        }
    
        [DbFunction("BD1Entities1", "StocCurentTB")]
        public virtual IQueryable<Nullable<int>> StocCurentTB(Nullable<int> idProdus, Nullable<int> idDepozit, Nullable<System.DateTime> data)
        {
            var idProdusParameter = idProdus.HasValue ?
                new ObjectParameter("IdProdus", idProdus) :
                new ObjectParameter("IdProdus", typeof(int));
    
            var idDepozitParameter = idDepozit.HasValue ?
                new ObjectParameter("IdDepozit", idDepozit) :
                new ObjectParameter("IdDepozit", typeof(int));
    
            var dataParameter = data.HasValue ?
                new ObjectParameter("Data", data) :
                new ObjectParameter("Data", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Nullable<int>>("[BD1Entities1].[StocCurentTB](@IdProdus, @IdDepozit, @Data)", idProdusParameter, idDepozitParameter, dataParameter);
        }
    
        [DbFunction("BD1Entities1", "CMP")]
        public virtual IQueryable<CMP_Result> CMP(Nullable<int> idProdus, Nullable<int> idDepozit, Nullable<System.DateTime> dataIesirii, Nullable<decimal> cantitateIesire)
        {
            var idProdusParameter = idProdus.HasValue ?
                new ObjectParameter("IdProdus", idProdus) :
                new ObjectParameter("IdProdus", typeof(int));
    
            var idDepozitParameter = idDepozit.HasValue ?
                new ObjectParameter("IdDepozit", idDepozit) :
                new ObjectParameter("IdDepozit", typeof(int));
    
            var dataIesiriiParameter = dataIesirii.HasValue ?
                new ObjectParameter("DataIesirii", dataIesirii) :
                new ObjectParameter("DataIesirii", typeof(System.DateTime));
    
            var cantitateIesireParameter = cantitateIesire.HasValue ?
                new ObjectParameter("CantitateIesire", cantitateIesire) :
                new ObjectParameter("CantitateIesire", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<CMP_Result>("[BD1Entities1].[CMP](@IdProdus, @IdDepozit, @DataIesirii, @CantitateIesire)", idProdusParameter, idDepozitParameter, dataIesiriiParameter, cantitateIesireParameter);
        }
    
        [DbFunction("BD1Entities1", "CMP_StocCurent")]
        public virtual IQueryable<CMP_StocCurent_Result> CMP_StocCurent(Nullable<int> idProdus, Nullable<int> idDepozit, Nullable<System.DateTime> dataIesirii, Nullable<decimal> cantitateIesire)
        {
            var idProdusParameter = idProdus.HasValue ?
                new ObjectParameter("IdProdus", idProdus) :
                new ObjectParameter("IdProdus", typeof(int));
    
            var idDepozitParameter = idDepozit.HasValue ?
                new ObjectParameter("IdDepozit", idDepozit) :
                new ObjectParameter("IdDepozit", typeof(int));
    
            var dataIesiriiParameter = dataIesirii.HasValue ?
                new ObjectParameter("DataIesirii", dataIesirii) :
                new ObjectParameter("DataIesirii", typeof(System.DateTime));
    
            var cantitateIesireParameter = cantitateIesire.HasValue ?
                new ObjectParameter("CantitateIesire", cantitateIesire) :
                new ObjectParameter("CantitateIesire", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<CMP_StocCurent_Result>("[BD1Entities1].[CMP_StocCurent](@IdProdus, @IdDepozit, @DataIesirii, @CantitateIesire)", idProdusParameter, idDepozitParameter, dataIesiriiParameter, cantitateIesireParameter);
        }
    
        [DbFunction("BD1Entities1", "CalculValoareIesireCMPTV")]
        public virtual IQueryable<CalculValoareIesireCMPTV_Result> CalculValoareIesireCMPTV(Nullable<int> idProdus, Nullable<int> idDepozit, Nullable<System.DateTime> dataIesire, Nullable<decimal> cantitate)
        {
            var idProdusParameter = idProdus.HasValue ?
                new ObjectParameter("IdProdus", idProdus) :
                new ObjectParameter("IdProdus", typeof(int));
    
            var idDepozitParameter = idDepozit.HasValue ?
                new ObjectParameter("IdDepozit", idDepozit) :
                new ObjectParameter("IdDepozit", typeof(int));
    
            var dataIesireParameter = dataIesire.HasValue ?
                new ObjectParameter("DataIesire", dataIesire) :
                new ObjectParameter("DataIesire", typeof(System.DateTime));
    
            var cantitateParameter = cantitate.HasValue ?
                new ObjectParameter("Cantitate", cantitate) :
                new ObjectParameter("Cantitate", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<CalculValoareIesireCMPTV_Result>("[BD1Entities1].[CalculValoareIesireCMPTV](@IdProdus, @IdDepozit, @DataIesire, @Cantitate)", idProdusParameter, idDepozitParameter, dataIesireParameter, cantitateParameter);
        }
    
        public virtual int ActualizareStocInitialSiPretLaFinalAn()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizareStocInitialSiPretLaFinalAn");
        }
    
        [DbFunction("BD1Entities1", "BalantaStocuri")]
        public virtual IQueryable<BalantaStocuri_Result> BalantaStocuri(Nullable<System.DateTime> dataInitial, Nullable<System.DateTime> dataFinal, Nullable<int> idDepozit)
        {
            var dataInitialParameter = dataInitial.HasValue ?
                new ObjectParameter("DataInitial", dataInitial) :
                new ObjectParameter("DataInitial", typeof(System.DateTime));
    
            var dataFinalParameter = dataFinal.HasValue ?
                new ObjectParameter("DataFinal", dataFinal) :
                new ObjectParameter("DataFinal", typeof(System.DateTime));
    
            var idDepozitParameter = idDepozit.HasValue ?
                new ObjectParameter("IdDepozit", idDepozit) :
                new ObjectParameter("IdDepozit", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<BalantaStocuri_Result>("[BD1Entities1].[BalantaStocuri](@DataInitial, @DataFinal, @IdDepozit)", dataInitialParameter, dataFinalParameter, idDepozitParameter);
        }
    
        [DbFunction("BD1Entities1", "BalantaProdusDetaliat")]
        public virtual IQueryable<BalantaProdusDetaliat_Result> BalantaProdusDetaliat(Nullable<System.DateTime> dataInitial, Nullable<System.DateTime> dataFinal, Nullable<int> idDepozit, Nullable<int> idProdus)
        {
            var dataInitialParameter = dataInitial.HasValue ?
                new ObjectParameter("DataInitial", dataInitial) :
                new ObjectParameter("DataInitial", typeof(System.DateTime));
    
            var dataFinalParameter = dataFinal.HasValue ?
                new ObjectParameter("DataFinal", dataFinal) :
                new ObjectParameter("DataFinal", typeof(System.DateTime));
    
            var idDepozitParameter = idDepozit.HasValue ?
                new ObjectParameter("IdDepozit", idDepozit) :
                new ObjectParameter("IdDepozit", typeof(int));
    
            var idProdusParameter = idProdus.HasValue ?
                new ObjectParameter("IdProdus", idProdus) :
                new ObjectParameter("IdProdus", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<BalantaProdusDetaliat_Result>("[BD1Entities1].[BalantaProdusDetaliat](@DataInitial, @DataFinal, @IdDepozit, @IdProdus)", dataInitialParameter, dataFinalParameter, idDepozitParameter, idProdusParameter);
        }
    
        public virtual int ActualizeazaStocInitialSiPret()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizeazaStocInitialSiPret");
        }
    
        [DbFunction("BD1Entities1", "FisaMagazie")]
        public virtual IQueryable<FisaMagazie_Result> FisaMagazie(Nullable<System.DateTime> dataInitial, Nullable<System.DateTime> dataFinal, Nullable<int> idDepozit, Nullable<int> idProdus)
        {
            var dataInitialParameter = dataInitial.HasValue ?
                new ObjectParameter("DataInitial", dataInitial) :
                new ObjectParameter("DataInitial", typeof(System.DateTime));
    
            var dataFinalParameter = dataFinal.HasValue ?
                new ObjectParameter("DataFinal", dataFinal) :
                new ObjectParameter("DataFinal", typeof(System.DateTime));
    
            var idDepozitParameter = idDepozit.HasValue ?
                new ObjectParameter("IdDepozit", idDepozit) :
                new ObjectParameter("IdDepozit", typeof(int));
    
            var idProdusParameter = idProdus.HasValue ?
                new ObjectParameter("IdProdus", idProdus) :
                new ObjectParameter("IdProdus", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FisaMagazie_Result>("[BD1Entities1].[FisaMagazie](@DataInitial, @DataFinal, @IdDepozit, @IdProdus)", dataInitialParameter, dataFinalParameter, idDepozitParameter, idProdusParameter);
        }
    
        [DbFunction("BD1Entities1", "FisaMagazie1")]
        public virtual IQueryable<FisaMagazie1_Result> FisaMagazie1(Nullable<System.DateTime> dataInitial, Nullable<System.DateTime> dataFinal, Nullable<int> idDepozit, Nullable<int> idProdus)
        {
            var dataInitialParameter = dataInitial.HasValue ?
                new ObjectParameter("DataInitial", dataInitial) :
                new ObjectParameter("DataInitial", typeof(System.DateTime));
    
            var dataFinalParameter = dataFinal.HasValue ?
                new ObjectParameter("DataFinal", dataFinal) :
                new ObjectParameter("DataFinal", typeof(System.DateTime));
    
            var idDepozitParameter = idDepozit.HasValue ?
                new ObjectParameter("IdDepozit", idDepozit) :
                new ObjectParameter("IdDepozit", typeof(int));
    
            var idProdusParameter = idProdus.HasValue ?
                new ObjectParameter("IdProdus", idProdus) :
                new ObjectParameter("IdProdus", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FisaMagazie1_Result>("[BD1Entities1].[FisaMagazie1](@DataInitial, @DataFinal, @IdDepozit, @IdProdus)", dataInitialParameter, dataFinalParameter, idDepozitParameter, idProdusParameter);
        }
    }
}
