//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestiunea_stocurilor
{
    using System;
    using System.Collections.Generic;
    
    public partial class NIR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NIR()
        {
            this.ContinutNIR = new HashSet<ContinutNIR>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdDepozit { get; set; }
        public Nullable<int> IdFactura { get; set; }
        public string Numar { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContinutNIR> ContinutNIR { get; set; }
        public virtual Depozit Depozit { get; set; }
        public virtual Factura Factura { get; set; }
    }
}
