//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestiunea_stocurilor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdusConsum
    {
        public int Id { get; set; }
        public Nullable<int> IdBonConsum { get; set; }
        public Nullable<int> IdProdus { get; set; }
        public Nullable<decimal> Cantitate { get; set; }
    
        public virtual BonConsum BonConsum { get; set; }
        public virtual Produs Produs { get; set; }
    }
}
