//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestiunea_stocurilor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produs()
        {
            this.ContinutFactura = new HashSet<ContinutFactura>();
            this.ContinutNIR = new HashSet<ContinutNIR>();
            this.ProdusConsum = new HashSet<ProdusConsum>();
            this.ProdusExpeditie = new HashSet<ProdusExpeditie>();
            this.ProdusGestionat = new HashSet<ProdusGestionat>();
            this.ProdusTransfer = new HashSet<ProdusTransfer>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Cod { get; set; }
        public string Denumire { get; set; }
        public string UnitateDeMasura { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContinutFactura> ContinutFactura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContinutNIR> ContinutNIR { get; set; }
        public virtual Marfa Marfa { get; set; }
        public virtual Material Material { get; set; }
        public virtual MateriePrima MateriePrima { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdusConsum> ProdusConsum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdusExpeditie> ProdusExpeditie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdusGestionat> ProdusGestionat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdusTransfer> ProdusTransfer { get; set; }
        public virtual ProdusFinit ProdusFinit { get; set; }
    }
}
